export default [
  {
    author: 'Chinua Achebe',
    country: 'Nigeria',
    language: 'English',
    pages: 209,
    title: 'Things Fall Apart',
    year: 1959,
    id: '1',
  },
  {
    author: 'Hans Christian Andersen',
    country: 'Denmark',
    language: 'Danish',
    pages: 784,
    title: 'Fairy tales',
    year: 1836,
    id: '2',
  },
  {
    author: 'Dante Alighieri',
    country: 'Italy',
    language: 'Italian',
    pages: 928,
    title: 'The Divine Comedy',
    year: 1315,
    id: '3',
  },
  {
    author: 'Unknown',
    country: 'Sumer and Akkadian Empire',
    language: 'Akkadian',
    pages: 160,
    title: 'The Epic Of Gilgamesh',
    year: -1700,
    id: '4',
  },
  {
    author: 'Unknown',
    country: 'Achaemenid Empire',
    language: 'Hebrew',
    pages: 176,
    title: 'The Book Of Job',
    year: -600,
    id: '5',
  },
  {
    author: 'Unknown',
    country: 'India/Iran/Iraq/Egypt/Tajikistan',
    language: 'Arabic',
    pages: 288,
    title: 'One Thousand and One Nights',
    year: 1200,
    id: '6',
  },
  {
    author: 'Unknown',
    country: 'Iceland',
    language: 'Old Norse',
    pages: 384,
    title: "Njál's Saga",
    year: 1350,
    id: '7',
  },
  {
    author: 'Jane Austen',
    country: 'United Kingdom',
    language: 'English',
    pages: 226,
    title: 'Pride and Prejudice',
    year: 1813,
    id: '8',
  },
  {
    author: 'Honoré de Balzac',
    country: 'France',
    language: 'French',
    pages: 443,
    title: 'Le Père Goriot',
    year: 1835,
    id: '9',
  },
  {
    author: 'Samuel Beckett',
    country: 'Republic of Ireland',
    language: 'French, English',
    pages: 256,
    title: 'Molloy, Malone Dies, The Unnamable, the trilogy',
    year: 1952,
    id: '10',
  },
  {
    author: 'Giovanni Boccaccio',
    country: 'Italy',
    language: 'Italian',
    pages: 1024,
    title: 'The Decameron',
    year: 1351,
    id: '11',
  },
  {
    author: 'Jorge Luis Borges',
    country: 'Argentina',
    language: 'Spanish',
    pages: 224,
    title: 'Ficciones',
    year: 1965,
    id: '12',
  },
  {
    author: 'Emily Brontë',
    country: 'United Kingdom',
    language: 'English',
    pages: 342,
    title: 'Wuthering Heights',
    year: 1847,
    id: '13',
  },
  {
    author: 'Albert Camus',
    country: 'Algeria, French Empire',
    language: 'French',
    pages: 185,
    title: 'The Stranger',
    year: 1942,
    id: '14',
  },
  {
    author: 'Paul Celan',
    country: 'Romania, France',
    language: 'German',
    pages: 320,
    title: 'Poems',
    year: 1952,
    id: '15',
  },
  {
    author: 'Louis-Ferdinand Céline',
    country: 'France',
    language: 'French',
    pages: 505,
    title: 'Journey to the End of the Night',
    year: 1932,
    id: '16',
  },
  {
    author: 'Miguel de Cervantes',
    country: 'Spain',
    language: 'Spanish',
    pages: 1056,
    title: 'Don Quijote De La Mancha',
    year: 1610,
    id: '17',
  },
  {
    author: 'Geoffrey Chaucer',
    country: 'England',
    language: 'English',
    pages: 544,
    title: 'The Canterbury Tales',
    year: 1450,
    id: '18',
  },
  {
    author: 'Anton Chekhov',
    country: 'Russia',
    language: 'Russian',
    pages: 194,
    title: 'Stories',
    year: 1886,
    id: '19',
  },
  {
    author: 'Joseph Conrad',
    country: 'United Kingdom',
    language: 'English',
    pages: 320,
    title: 'Nostromo',
    year: 1904,
    id: '20',
  },
  {
    author: 'Charles Dickens',
    country: 'United Kingdom',
    language: 'English',
    pages: 194,
    title: 'Great Expectations',
    year: 1861,
    id: '21',
  },
  {
    author: 'Denis Diderot',
    country: 'France',
    language: 'French',
    pages: 596,
    title: 'Jacques the Fatalist',
    year: 1796,
    id: '22',
  },
  {
    author: 'Alfred Döblin',
    country: 'Germany',
    language: 'German',
    pages: 600,
    title: 'Berlin Alexanderplatz',
    year: 1929,
    id: '23',
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 551,
    title: 'Crime and Punishment',
    year: 1866,
    id: '24',
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 656,
    title: 'The Idiot',
    year: 1869,
    id: '25',
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 768,
    title: 'The Possessed',
    year: 1872,
    id: '26',
  },
  {
    author: 'Fyodor Dostoevsky',
    country: 'Russia',
    language: 'Russian',
    pages: 824,
    title: 'The Brothers Karamazov',
    year: 1880,
    id: '27',
  },
  {
    author: 'George Eliot',
    country: 'United Kingdom',
    language: 'English',
    pages: 800,
    title: 'Middlemarch',
    year: 1871,
    id: '28',
  },
  {
    author: 'Ralph Ellison',
    country: 'United States',
    language: 'English',
    pages: 581,
    title: 'Invisible Man',
    year: 1952,
    id: '29',
  },
  {
    author: 'Euripides',
    country: 'Greece',
    language: 'Greek',
    pages: 104,
    title: 'Medea',
    year: -431,
    id: '30',
  },
  {
    author: 'William Faulkner',
    country: 'United States',
    language: 'English',
    pages: 313,
    title: 'Absalom, Absalom!',
    year: 1936,
    id: '31',
  },
  {
    author: 'William Faulkner',
    country: 'United States',
    language: 'English',
    pages: 326,
    title: 'The Sound and the Fury',
    year: 1929,
    id: '32',
  },
  {
    author: 'Gustave Flaubert',
    country: 'France',
    language: 'French',
    pages: 528,
    title: 'Madame Bovary',
    year: 1857,
    id: '33',
  },
  {
    author: 'Gustave Flaubert',
    country: 'France',
    language: 'French',
    pages: 606,
    title: 'Sentimental Education',
    year: 1869,
    id: '34',
  },
  {
    author: 'Federico García Lorca',
    country: 'Spain',
    language: 'Spanish',
    pages: 218,
    title: 'Gypsy Ballads',
    year: 1928,
    id: '35',
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 417,
    title: 'One Hundred Years of Solitude',
    year: 1967,
    id: '36',
  },
  {
    author: 'Gabriel García Márquez',
    country: 'Colombia',
    language: 'Spanish',
    pages: 368,
    title: 'Love in the Time of Cholera',
    year: 1985,
    id: '37',
  },
  {
    author: 'Johann Wolfgang von Goethe',
    country: 'Saxe-Weimar',
    language: 'German',
    pages: 158,
    title: 'Faust',
    year: 1832,
    id: '38',
  },
  {
    author: 'Nikolai Gogol',
    country: 'Russia',
    language: 'Russian',
    pages: 432,
    title: 'Dead Souls',
    year: 1842,
    id: '39',
  },
  {
    author: 'Günter Grass',
    country: 'Germany',
    language: 'German',
    pages: 600,
    title: 'The Tin Drum',
    year: 1959,
    id: '40',
  },
  {
    author: 'João Guimarães Rosa',
    country: 'Brazil',
    language: 'Portuguese',
    pages: 494,
    title: 'The Devil to Pay in the Backlands',
    year: 1956,
    id: '41',
  },
  {
    author: 'Knut Hamsun',
    country: 'Norway',
    language: 'Norwegian',
    pages: 176,
    title: 'Hunger',
    year: 1890,
    id: '42',
  },
  {
    author: 'Ernest Hemingway',
    country: 'United States',
    language: 'English',
    pages: 128,
    title: 'The Old Man and the Sea',
    year: 1952,
    id: '43',
  },
  {
    author: 'Homer',
    country: 'Greece',
    language: 'Greek',
    pages: 608,
    title: 'Iliad',
    year: -735,
    id: '44',
  },
  {
    author: 'Homer',
    country: 'Greece',
    language: 'Greek',
    pages: 374,
    title: 'Odyssey',
    year: -800,
    id: '45',
  },
  {
    author: 'Henrik Ibsen',
    country: 'Norway',
    language: 'Norwegian',
    pages: 68,
    title: "A Doll's House",
    year: 1879,
    id: '46',
  },
  {
    author: 'James Joyce',
    country: 'Irish Free State',
    language: 'English',
    pages: 228,
    title: 'Ulysses',
    year: 1922,
    id: '47',
  },
  {
    author: 'Franz Kafka',
    country: 'Czechoslovakia',
    language: 'German',
    pages: 488,
    title: 'Stories',
    year: 1924,
    id: '48',
  },
  {
    author: 'Franz Kafka',
    country: 'Czechoslovakia',
    language: 'German',
    pages: 160,
    title: 'The Trial',
    year: 1925,
    id: '49',
  },
  {
    author: 'Franz Kafka',
    country: 'Czechoslovakia',
    language: 'German',
    pages: 352,
    title: 'The Castle',
    year: 1926,
    id: '50',
  },
  {
    author: 'Kālidāsa',
    country: 'India',
    language: 'Sanskrit',
    pages: 147,
    title: 'The recognition of Shakuntala',
    year: 150,
    id: '51',
  },
  {
    author: 'Yasunari Kawabata',
    country: 'Japan',
    language: 'Japanese',
    pages: 288,
    title: 'The Sound of the Mountain',
    year: 1954,
    id: '52',
  },
  {
    author: 'Nikos Kazantzakis',
    country: 'Greece',
    language: 'Greek',
    pages: 368,
    title: 'Zorba the Greek',
    year: 1946,
    id: '53',
  },
  {
    author: 'D. H. Lawrence',
    country: 'United Kingdom',
    language: 'English',
    pages: 432,
    title: 'Sons and Lovers',
    year: 1913,
    id: '54',
  },
  {
    author: 'Halldór Laxness',
    country: 'Iceland',
    language: 'Icelandic',
    pages: 470,
    title: 'Independent People',
    year: 1934,
    id: '55',
  },
  {
    author: 'Giacomo Leopardi',
    country: 'Italy',
    language: 'Italian',
    pages: 184,
    title: 'Poems',
    year: 1818,
    id: '56',
  },
  {
    author: 'Doris Lessing',
    country: 'United Kingdom',
    language: 'English',
    pages: 688,
    title: 'The Golden Notebook',
    year: 1962,
    id: '57',
  },
  {
    author: 'Astrid Lindgren',
    country: 'Sweden',
    language: 'Swedish',
    pages: 160,
    title: 'Pippi Longstocking',
    year: 1945,
    id: '58',
  },
  {
    author: 'Lu Xun',
    country: 'China',
    language: 'Chinese',
    pages: 389,
    title: 'Diary of a Madman',
    year: 1918,
    id: '59',
  },
  {
    author: 'Naguib Mahfouz',
    country: 'Egypt',
    language: 'Arabic',
    pages: 355,
    title: 'Children of Gebelawi',
    year: 1959,
    id: '60',
  },
  {
    author: 'Thomas Mann',
    country: 'Germany',
    language: 'German',
    pages: 736,
    title: 'Buddenbrooks',
    year: 1901,
    id: '61',
  },
  {
    author: 'Thomas Mann',
    country: 'Germany',
    language: 'German',
    pages: 720,
    title: 'The Magic Mountain',
    year: 1924,
    id: '62',
  },
  {
    author: 'Herman Melville',
    country: 'United States',
    language: 'English',
    pages: 378,
    title: 'Moby Dick',
    year: 1851,
    id: '63',
  },
  {
    author: 'Michel de Montaigne',
    country: 'France',
    language: 'French',
    pages: 404,
    title: 'Essays',
    year: 1595,
    id: '64',
  },
  {
    author: 'Elsa Morante',
    country: 'Italy',
    language: 'Italian',
    pages: 600,
    title: 'History',
    year: 1974,
    id: '65',
  },
  {
    author: 'Toni Morrison',
    country: 'United States',
    language: 'English',
    pages: 321,
    title: 'Beloved',
    year: 1987,
    id: '66',
  },
  {
    author: 'Murasaki Shikibu',
    country: 'Japan',
    language: 'Japanese',
    pages: 1360,
    title: 'The Tale of Genji',
    year: 1006,
    id: '67',
  },
  {
    author: 'Robert Musil',
    country: 'Austria',
    language: 'German',
    pages: 365,
    title: 'The Man Without Qualities',
    year: 1931,
    id: '68',
  },
  {
    author: 'Vladimir Nabokov',
    country: 'Russia/United States',
    language: 'English',
    pages: 317,
    title: 'Lolita',
    year: 1955,
    id: '69',
  },
  {
    author: 'George Orwell',
    country: 'United Kingdom',
    language: 'English',
    pages: 272,
    title: 'Nineteen Eighty-Four',
    year: 1949,
    id: '70',
  },
  {
    author: 'Ovid',
    country: 'Roman Empire',
    language: 'Classical Latin',
    pages: 576,
    title: 'Metamorphoses',
    year: 100,
    id: '71',
  },
  {
    author: 'Fernando Pessoa',
    country: 'Portugal',
    language: 'Portuguese',
    pages: 272,
    title: 'The Book of Disquiet',
    year: 1928,
    id: '72',
  },
  {
    author: 'Edgar Allan Poe',
    country: 'United States',
    language: 'English',
    pages: 842,
    title: 'Tales',
    year: 1950,
    id: '73',
  },
  {
    author: 'Marcel Proust',
    country: 'France',
    language: 'French',
    pages: 2408,
    title: 'In Search of Lost Time',
    year: 1920,
    id: '74',
  },
  {
    author: 'François Rabelais',
    country: 'France',
    language: 'French',
    pages: 623,
    title: 'Gargantua and Pantagruel',
    year: 1533,
    id: '75',
  },
  {
    author: 'Juan Rulfo',
    country: 'Mexico',
    language: 'Spanish',
    pages: 124,
    title: 'Pedro Páramo',
    year: 1955,
    id: '76',
  },
  {
    author: 'Rumi',
    country: 'Sultanate of Rum',
    language: 'Persian',
    pages: 438,
    title: 'The Masnavi',
    year: 1236,
    id: '77',
  },
  {
    author: 'Salman Rushdie',
    country: 'United Kingdom, India',
    language: 'English',
    pages: 536,
    title: "Midnight's Children",
    year: 1981,
    id: '78',
  },
  {
    author: 'Saadi',
    country: 'Persia, Persian Empire',
    language: 'Persian',
    pages: 298,
    title: 'Bostan',
    year: 1257,
    id: '79',
  },
  {
    author: 'Tayeb Salih',
    country: 'Sudan',
    language: 'Arabic',
    pages: 139,
    title: 'Season of Migration to the North',
    year: 1966,
    id: '80',
  },
  {
    author: 'José Saramago',
    country: 'Portugal',
    language: 'Portuguese',
    pages: 352,
    title: 'Blindness',
    year: 1995,
    id: '81',
  },
  {
    author: 'William Shakespeare',
    country: 'England',
    language: 'English',
    pages: 432,
    title: 'Hamlet',
    year: 1603,
    id: '82',
  },
  {
    author: 'William Shakespeare',
    country: 'England',
    language: 'English',
    pages: 384,
    title: 'King Lear',
    year: 1608,
    id: '83',
  },
  {
    author: 'William Shakespeare',
    country: 'England',
    language: 'English',
    pages: 314,
    title: 'Othello',
    year: 1609,
    id: '84',
  },
  {
    author: 'Sophocles',
    country: 'Greece',
    language: 'Greek',
    pages: 88,
    title: 'Oedipus the King',
    year: -430,
    id: '85',
  },
  {
    author: 'Stendhal',
    country: 'France',
    language: 'French',
    pages: 576,
    title: 'The Red and the Black',
    year: 1830,
    id: '86',
  },
  {
    author: 'Laurence Sterne',
    country: 'England',
    language: 'English',
    pages: 640,
    title: 'The Life And Opinions of Tristram Shandy',
    year: 1760,
    id: '87',
  },
  {
    author: 'Italo Svevo',
    country: 'Italy',
    language: 'Italian',
    pages: 412,
    title: 'Confessions of Zeno',
    year: 1923,
    id: '88',
  },
  {
    author: 'Jonathan Swift',
    country: 'Ireland',
    language: 'English',
    pages: 178,
    title: "Gulliver's Travels",
    year: 1726,
    id: '89',
  },
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 1296,
    title: 'War and Peace',
    year: 1867,
    id: '90',
  },
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 864,
    title: 'Anna Karenina',
    year: 1877,
    id: '91',
  },
  {
    author: 'Leo Tolstoy',
    country: 'Russia',
    language: 'Russian',
    pages: 92,
    title: 'The Death of Ivan Ilyich',
    year: 1886,
    id: '92',
  },
  {
    author: 'Mark Twain',
    country: 'United States',
    language: 'English',
    pages: 224,
    title: 'The Adventures of Huckleberry Finn',
    year: 1884,
    id: '93',
  },
  {
    author: 'Valmiki',
    country: 'India',
    language: 'Sanskrit',
    pages: 152,
    title: 'Ramayana',
    year: -450,
    id: '94',
  },
  {
    author: 'Virgil',
    country: 'Roman Empire',
    language: 'Classical Latin',
    pages: 442,
    title: 'The Aeneid',
    year: -23,
    id: '95',
  },
  {
    author: 'Vyasa',
    country: 'India',
    language: 'Sanskrit',
    pages: 276,
    title: 'Mahabharata',
    year: -700,
    id: '96',
  },
  {
    author: 'Walt Whitman',
    country: 'United States',
    language: 'English',
    pages: 152,
    title: 'Leaves of Grass',
    year: 1855,
    id: '97',
  },
  {
    author: 'Virginia Woolf',
    country: 'United Kingdom',
    language: 'English',
    pages: 216,
    title: 'Mrs Dalloway',
    year: 1925,
    id: '98',
  },
  {
    author: 'Virginia Woolf',
    country: 'United Kingdom',
    language: 'English',
    pages: 209,
    title: 'To the Lighthouse',
    year: 1927,
    id: '99',
  },
  {
    author: 'Marguerite Yourcenar',
    country: 'France/Belgium',
    language: 'French',
    pages: 408,
    title: 'Memoirs of Hadrian',
    year: 1951,
    id: '100',
  },
];
